[View in Colaboratory](https://colab.research.google.com/github/margaretmz/deep-learning/blob/master/tensorflow_basics.ipynb)

# Intro to TensorFlow
A brief intro to TensorFlow basics and low level API

Margaret Maynard-Reid, 6/12/2018



>[Intro to TensorFlow](#scrollTo=n3xq7WWDpWAL)

>>[TensorFlow basics](#scrollTo=9Tn30IjOuGlS)

>>>[tf.constant](#scrollTo=DzwxAlIIMpwC)

>>>[tf.placeholder](#scrollTo=jzqCrrLbMtYL)

>>>[tf.matmul](#scrollTo=LtLEpuCjMxlY)

>>[Tensor shapes](#scrollTo=nSXMrfa2LWXR)

>>[Numpy vs. Graph Execution vs. Eager Execution](#scrollTo=IoVjopDMUh20)

>>>[Numpy example](#scrollTo=P1-h74q6TOco)

>>>[Graph Execution](#scrollTo=TkoB7-iFNPbY)

>>>[Eager Execution](#scrollTo=BjiF22vwNiR6)



## TensorFlow basics

*   tf.constant - the value of the tensor never changes
*   tf.placeholder - returns a tensor that gets values from data passed to tf.session.run(), for example, training dataset
*   tf.variable - a tensor with an initial value that can be modified, example: weights and biases

In [0]:
import tensorflow as tf

### tf.constant

In [3]:
# Create TensorFlow object called hello_constant
hello_constant = tf.constant('Hello TensorFlow!')

with tf.Session() as sess:
    # Run the tf.constant operation in the session
    output = sess.run(hello_constant)
    print(output)

b'Hello TensorFlow!'


### tf.placeholder

In [4]:
x = tf.placeholder(tf.string)

with tf.Session() as sess:
    output = sess.run(x, feed_dict={x: 'Hello TensorFlow'})
    print(output)

Hello TensorFlow


### tf.matmul

In [7]:
with tf.Graph().as_default():
  # Create a matrix (2-d tensor) with 3 rows and 4 columns.
  x = tf.constant([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
                  dtype=tf.int32)

  # Create a matrix with 4 rows and 2 columns.
  y = tf.constant([[2, 2], [3, 5], [4, 5], [1, 6]], dtype=tf.int32)

  # Multiply `x` by `y`
  # Make sure the number of columns in x matches the number of rows in y
  # The resulting matrix will have 3 rows and 2 columns
  matrix_multiply_result = tf.matmul(x, y)
  
  with tf.Session() as sess:
    print(matrix_multiply_result.eval())

[[ 24  51]
 [ 64 123]
 [104 195]]


## Tensor shapes

In [14]:
with tf.Graph().as_default():
  # A scalar (0-D tensor) of 1
  scalar = tf.ones([])

  # A vector with 3 elements of 1's
  vector = tf.ones([3])

  # A matrix with 3 rows and 3 columns of 1's
  matrix = tf.ones([3, 3])

  with tf.Session() as sess:
    print('scalar shape', scalar.get_shape(), 'and value:\n', scalar.eval())
    print('vector shape', vector.get_shape(), 'and value:\n', vector.eval())
    print('matrix shape', matrix.get_shape(), 'and value:\n', matrix.eval())

scalar shape () and value:
 1.0
vector shape (3,) and value:
 [1. 1. 1.]
matrix shape (3, 3) and value:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## Numpy vs. Graph Execution vs. Eager Execution

### Numpy example

In [4]:
import numpy as np
a = np.array([1, 2])
b = np.array ([3, 4])
c = np.add (a, b)
print (c)

[4 6]


### Graph Execution
In TensorFlow graph execution (default), you must first create a session and run the session to build the graph

In [3]:
# Example in TensorFLow
a = tf.constant([1,2])
b = tf.constant([3,4])
c = tf.add(a, b)
print ("What's in c before running Session.run() - ", c)

with tf.Session() as sess:
  result = sess.run(c)
  print ("What's in c after running Session.run() - ", result)

What's in c before running Session.run() -  Tensor("Add:0", shape=(2,), dtype=int32)
What's in c after running Session.run() -  [4 6]


### Eager Execution
Note: 

Please click on "Runtime/restart runtime" or create a **new **notebook and enable eager execution there before running the code below. 

Eager Execution is only available in TensorFlow 1.8+.  Be sure to have ***!pip install -q --upgrade tensorflow*** at the beginning of your program

In [0]:
import tensorflow as tf
# Enable eager execution
tf.enable_eager_execution()

In [3]:
# Notice the code here is very similar to the Numpy example above, no need to create a Tensorflow session in order to see what's in c
a = tf.constant([1,2])
b = tf.constant([3,4])
c = tf.add(a, b)
print ("What's in c with eager execution? - ", c)

What's in c with eager execution? -  tf.Tensor([4 6], shape=(2,), dtype=int32)
